[package]
name = "oppskritf-api"
version = "0.0.2"
authors = ["Charles <charles.capelli@qonfucius.team>", "Djyp <d@plus.yt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-web = "3"
actix-rt = "1.1"
diesel = { version = "1.4.5", features = ["postgres"] }